<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditUsers.aspx.cs" Inherits="VegiJ.Web.Users.Administration.EditUsers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="editUsersGrid" runat="server" ItemType="VegiJ.DataAccess.User"
        DataKeyNames="ID" SelectMethod="editUsersGrid_GetData" UpdateMethod="editUsersGrid_UpdateItem"
        DeleteMethod="editUsersGrid_DeleteItem"  AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false" >

    </asp:GridView>
</asp:Content>
